### ISSUE TITLE
Misc.9 Client Side User Cache Services

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#102]
## User Story
Implement client side user cache service to reduce the number of calls to the database

## Sub-Tasks
- [ ] create user services that uses local/session storage to cache and retrieve data
- [ ] create user services that first call the local storage service. On cache miss, use the Firebase service version to retrieve the data. Posts/Puts should save data in both locally and remotely
- [ ] Update providers in the app config file if necessary
