### ISSUE TITLE
H.1 Create Recent Carousel

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#11]
## User Story
As a user, I want to be able to easily view and recognize my recently accessed sets, so that I can readily find a specific set 

## Sub-tasks
- [x] Create recent card component 
- [x] Fetch relevant information from database 
  - User’s recent sets 
  - Study set information 
- [x] Create dot progress bar 
- [x] Create left and right navigation buttons 

## Notes
- Depends on #17
