### ISSUE TITLE
Misc.3 Create Top Navbar component

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#12]
## User Story
As a user, I want to be able to access all important features of the Ponder study app in a convenient place on every page, so I can more easily navigate through the app. 

## Sub-tasks
- [ ] Create UI design component 
- [ ] Add button to navigate to Create study set page 
- [ ] Add title/button for navigating to homepage 
- [ ] Add button for account sign out 
- [ ] Create pre-sign in top navbar version that only shows logo 

## Notes
- Have empty event handler on button clicks. Navigation will be another issue once skeleton pages are created
