### ISSUE TITLE
Misc.13 Client Side Study Set Cache Services

### ISSUE THREAD

**Issue by B-Yamawaki** [PonderTeam/ponder-app#123]
## User Story
Implement client side study set cache service to reduce the number of calls to the database

## Sub-Tasks
- [ ] create study set service that uses local/session storage to cache and retrieve data
- [ ] create study set service that first call the local storage service. On cache miss, use the Firebase service version to retrieve the data. Posts/Puts should save data in both locally and remotely
- [ ] Update providers in the app config file if necessary
