### ISSUE TITLE
Misc.4 Add Cloud Database

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#15]
## User Story
As a user, the study sets I create should be saved and stored so other users and I can access them on different devices. 

## Sub-tasks
- [ ] Design database schema 
- [ ] Implement on google cloud 
- [ ] Integrate backend API in front end app
