### ISSUE TITLE
H.2 Create User's Sets List

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#16]
## User Story
As a user, I want to be able to easily view my sets that I have recently interacted with

## Sub-tasks
- [x] Create list view of cards
- [x] Fetch relevant information
- [x] Create scrolling list of "my" sets
- [x] Add component to Homepage 

## Notes
- Depends on #17
