### ISSUE TITLE
EC.2 Add Done Button

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#19]
## User Story
As a user, I want to navigate away from the edit card page, so that I can view my flashcards and study them.  

## Sub-tasks
- [x] Create button in UI
    - Make button clickable
- [x] Click actions
    - [x] Save study set and send to persistent data storage
    - [x] Navigate to View study set page

## Notes
- Depends on #57 and #14
