### ISSUE TITLE
ECF.1 Add list of Card Previews

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#21]
## User Story 
As a user, I want the front and back of cards to be previewed in a list so I can see all of them in a set.

## Sub-tasks 
- [x] Card preview component 
  - If you want to use the html and scss of the flashcard component, we may need to have a base flashcard component and also a flippable-flashcard-component. Or idk somehow stop the flipping.
  - Front/back and hamburger (no functionality needed)
- [x] Scrollable list of previews
- [x] Selected card indicators

## Notes
- depends on #20 
![Image](https://github.com/PonderTeam/ponder-app/assets/80545567/47193c38-7a10-4bd8-94b9-da8ac5e1375f)
- On Edit Create Study Set page, in Flasacard-editor component
- You do not need to implement adding cards
