### ISSUE TITLE
ECF.2 Add Flashcard to study set feature

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#22]
## User Story 
As a user, I want cards to place in my study set, so that I can build a set to study from.

## Sub-tasks
- [ ] Create two rectangular shapes that sit next to each other
  - [ ] Make these the correct color
  - [ ] Make the corners rounded Add text fields on the front and back
- These are not editable but display any text added to the front or back of a card.
