### ISSUE TITLE
ECF.6 Support rich text on flashcards

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#25]
## User Story
As a user, I want to use rich text on my flashcards, so I can emphasize and differentiate text.

## Sub-tasks
- [ ] Add rich text icons to flashcard editor UI 
  - Bold, italic underlining 
- [ ] Encode rich text (often done using html or md) 
- [ ] Save encoded rich text to study set data 
- [ ] Update UI views to support rich text 

## Notes
- depends on #24 
- You can use a rich text editor import like CKeditor or tinyMCE
