### ISSUE TITLE
ECF.7 Support adding image to flashcards (Dev)

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#27]
## User Story 
As a user, I want to add images to the back of my card, so that I can have additional aid to help me study the topic I want to learn.

## Sub-tasks 
- [x] Create image icon
- [x] Make image icon selectable
- [x] On icon press, Window opens that allow user to drag and drop or select a file to add to their flashcard
  - If low on time, open user’s file system only (not supporting drag and drop)
- [ ] Update flashcard data (in memory)
- [ ] Update flashcard data to hold image data 
  - Do not want to keep image loaded in memory entire time, so cache image unless on screen (lazy loading) and only save pointer to cache location 
- [ ] Update study set saving mechanism (pressing done) to send image file to remote image storage system and return image location key 
  - Study set textual data must include the image key before sending updated study set data to remote data storage

## Note
- images are not saved in the same database as the flashcard textual data. Instead, a flashcard has the address/key of the image in a separate image storage system. Encoding images is slow and should not be done. This also allows for lazy loading of images
- depends on #24 #22
