### ISSUE TITLE
ECF.8 Add delete card button

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#28]
## User Story
As a user, I want to be able to delete a card, so I do not have unneeded cards in my study set.

## Sub-tasks
- [ ] Add button icon 
- [ ] Make button clickable 
- [ ] Upon click, the card is deleted
