### ISSUE TITLE
ECS.1. Implement sequence creation

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#29]
## User Story
As a user, I want to add a sequence, so that I can populate sequences within my study set.

## Sub-tasks
- [x] Include a list of sequences that display the sequences in the study set in the correct place in the sequence-editor
- [x] Implement an Add button to create a sequence which also creates and adds the sequence to the data model
  - [x] For now, have the sequence be assigned a default name when created
  - [x] The button may already been added and you may just need to add its functionality.

## Notes
-  depends on #20 
![Image](https://github.com/PonderTeam/ponder-app/assets/80545567/32f652d2-ce4c-4cad-8b59-38bb31aad61c)
- On Edit Create Sequence page, make edits in the sequence-editor component
- You DO NOT need to include the trash cans, the sequence display at the right, or renaming of sequences
