### ISSUE TITLE
ECS.2 Support sequence select/delete

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#30]
## User Story
AS a user, I want to select a sequence, so that I can identify sequences within my study set

## Sub-tasks
- [x] Sequence name is clickable/selectable
- [ ] Selecting a sequence retrieves locally stored card order
- [x] Delete icon for every sequence name
- [x] Sequence deleted when icon is clicked
- [ ] Update study set state 

## Notes
- depends on #29 #20 
![Image](https://github.com/PonderTeam/ponder-app/assets/80545567/f86197cf-887e-4301-8373-66ff57166adf)
- On edit create study set. In the sequence-editor component
- trashcan reference from sequence card, expand icon
