### ISSUE TITLE
ECS.3 Select card for sequence

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#31]
## User Story
As a user, I want to select a card so that I know which card to add in the sequence

## Sub-tasks
- [ ] Display all cards in the set in scrollable menu
- [ ] Name of cards are clickable and highlighted to signify selection
- [ ] Use the flippable card component to create a preview
- [ ] Card preview is updated with user’s selected card.

## Notes
- depends on #20
![Image](https://github.com/PonderTeam/ponder-app/assets/80545567/149bd93d-cf41-4daa-b744-28d81cd4d02d)
- On Edit Create Study Set, in sequence-editor component
- You DO NOT need to do the sequences section, the arrows for the card preview, the add to sequence button, or the search bar
