### ISSUE TITLE
ECS.4 Add card to sequence

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#32]
## User Story
As a user, I want to add a card in a sequence, so that I can populate my study sequences

## Sub-tasks 
- [ ] Create "Add to sequence" button in card preview box
- [ ] Sequence order preview updated with card in the sequence
  - [ ] Can use the preview card created for edit/create flashcard, but need to add a (-) button
- [ ] Once added to the sequence order preview, button disappears (Ashley doesn't agree with this)

## Notes
- depends on #31
