### ISSUE TITLE
ECS.5 Remove card in sequence

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#33]
## User Story 
As a user, I want to remove a card in a sequence, so that I can remove any unneeded terms

## Sub-tasks 
- [ ] Delete button in sequence order preview
- [ ] Sequence order preview is updated to remove the selected card
- [ ] Card preview’s add to sequence button reappear for the selected card
