### ISSUE TITLE
ECS.6 Support sequence reordering

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#34]
## User Story 
As a user, I want to drag and rearrange cards in a sequence, so that I can easily edit the sequence ordering.

## Sub-tasks 
- [ ] Hamburger icon clickable and draggable
- [ ] Rearranging card by dragging is updated on the sequence order preview
- [ ] Update study set state

## Notes
- depends on #32 #29
