### ISSUE TITLE
Seq.1 Create Card Pool

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#37]
## User Story 
As a user, I want to have all the cards laid out for me, so that I can assess all the cards in the set.

## Sub-tasks 
- [x] Import study set data using study-set service object
- [x] Create sequence cards based on study set data
- [x] Formatting cards on the screen (look at homes app for ideas, probably a grid display)
- [x] Scroll

## Notes
- Depends on #58 
![Image](https://github.com/PonderTeam/ponder-app/assets/80545567/fe6a120c-4712-4741-b28e-1b33498d8ec2)
- On study sequence page
- You DO NOT have to implement adding or enlarging
