### ISSUE TITLE
Seq.2 Create Sequence Side Bar

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#38]
## User Story 

As a user, I want to see the sequence that I have built, so that I can visualize the creation of my sequence 

## Sub-tasks 

- [x] Create card slot/backing
- [x] Scroll 
- [x] Fill sequence with sample cards for testing
- [ ] The Sequence should be implemented in a way so we could compare the built sequence with a stored sequence
- [x] New slots/backing should only appear after a card is added changing dynamically. If you don't understand talk to Ben

## Notes:
- depends on #39 #58 
![Image](https://github.com/PonderTeam/ponder-app/assets/80545567/848f3c88-4861-49cf-a363-e23b7c7b54ca)
- On Study Sequence page
- You do not have to implement removing or enlarging
