### ISSUE TITLE
Seq.11 Create study sequence page (Parent)

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#39]
## User Story 
As a user, I want all tools for studying a sequence on one page, so I can easily find what I need.

## Sub-tasks 
- [ ] Retrieve Study Set info from Data Source
- [x] Create new page component
- [x] Add navbar
- [x] Create containers for card pool and sequence side bar components.

## Notes
- depends on #12 #14
