### ISSUE TITLE
SR.1 Create/implement search bar

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#4]
## User Story
As a user, I want to be able to search through all study sets available on the app, so I can find the one I want to study. 

## Sub-tasks
- [x] Create search bar UI component and add to Top NavBar
- [x] Create filter and apply it to backend database search
- [x] If time allows, cache popular/recent searches and make suggestions to user

## Notes
- Depends on #12 and #14

**Comment by ashkjones** [comment]
- Used Typesense to implement search. It links to our firestore and automatically updates on study-set creation, edits, and deletes.
- Query suggestions are also handled by typesense
