### ISSUE TITLE
Seq.3 Select Sequence to Study

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#40]
## User Story 
As a user, I want to select various sequences, so that I can seamlessly transition from studying one sequence to another. 

## Sub-tasks 

- [ ] Getting info of sequences 
- [ ] Displaying sequence menu 
- [ ] Setting selected sequence

## Notes
- depends on #39
