### ISSUE TITLE
Seq.4 Enlarged Card View

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#41]
## User Story 
As a user, I want to be able to enlarge the cards, so that I can clearly see and assess the position of each card. 

## Sub-tasks 

- [x] Add enlarge button in pond state and sequence state of sequence card
- [x] Create large flashcard component
- [ ] Display Large card 
- [x] Closing enlarged view 

## Notes 
- depends on #58

**Comment by ashkjones** [comment]
Also, styles can't be applied to `<ng-template>`. The `<ng-template>` is not rendered in Angular, only what is inside of it is added to the DOM
https://github.com/PonderTeam/ponder-app/blob/7c60ab21e911c6e282ceab62c17adcfb322088a6/src/app/sequence-card/sequence-card.component.html#L12

See the angular documentation for more information on `ng-template` https://angular.io/guide/structural-directives#the-ng-template

**Comment by B-Yamawaki** [comment]
Don't forget, we are also going to be removing the flipping of the sequence card as it causes some problems when it comes to dragging. The user story was not updated, but as we discussed on Monday removing the flipping on the sequence card is part of your task for this sprint.
