### ISSUE TITLE
Seq.5 Add card to Sequence Side Bar

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#42]
## User Story 
As a user, I want to add cards to a sequence, so I can test my knowledge on the ordering of terms. 

## Sub-tasks 
- [ ] Reformat cards in pond
- [ ] Format cards in sequence 
- [ ] Dragging card into sequence 
- [ ] Add buttons for cards 
- [ ] Changing the card slots in the sequence builder 

## Notes

**Comment by ashkjones** [comment]
Adding using the button has been implemented already. Reach out to me if you need help with implementing the dragging. We have discussed removing the flip on click to improve UX and make handling the click events easier.
