### ISSUE TITLE
Seq.6 Reorder Sequence in Sequence Side Bar

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#43]
## User Story 
As a user, I want to be able to reorder/reorganize the cards in a sequence, so I have more flexibility in adding cards to the sequence and creating my desired sequence. 

## Sub-tasks 
- [x] Show cards moving as the card is dragged 
- [x] Maintain backing data structure 
- [x] Scroll the window when card is drag dragged at the bottom 

## Notes
- depends on #38
- I would look at the dragging in edit/create flashcard and/or edit/create sequence. Understand how those work and then use a similar structure for this.
