### ISSUE TITLE
Seq.7 Remove Card from Sequence Side Bar

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#44]
## User Story 
As a user, I want to remove cards from the sequence, so that I can correct my mistakes when I add cards to the sequence that I no longer want 

## Sub-tasks 
- [x] Dragging cards into the pond 
- [x] Modify Sequence Card with - button
- [x] Clicking cards into the pond 
- [x] Change Sequence Card back to pond state "plus button"
- [x] Changing card slots 

## Notes
- depends on #37 #38
- This task is mainly about dragging the card out of the sequence. I would do this in conjunction with #42 and after #43
