### ISSUE TITLE
Seq.9 Check Sequence Answer

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#46]
## User Story 
As a user, I want to be able to check my built sequence, so that I can verify my proficiency with and understanding of the subject. 

## Sub-tasks 
- [ ] Check Sequence button 
- [ ] Display correct/incorrect 
- [ ] Verify from selected sequence 

## Notes
-  depends on #38
