### ISSUE TITLE
Seq.10 Show Sequence Answer

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#47]
## User Story 
As a user, I want to be able to reveal the answer, so that if I get stuck, I have an accessible way to help inform me. 

## Sub-tasks 
- [ ] Check Answer Button 
- [ ] Remove all incorrect cards 
- [ ] Add all correct cards in order 

## Notes
- depends on #42 #45
