### ISSUE TITLE
F.1 Create Flashcard Component

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#49]
## User Story 
As user, I want to be able to see the front and back of the flashcard that I made, so that I can study the flashcard 

## Sub-tasks 
- [ ] Create abstract component for flashcard
- [ ] Create concrete flashcard object front and back 
- [ ] Render the flashcard front and back
- [ ] Add to Study Flashcard Page component
