### ISSUE TITLE
F.5 Return to View Page

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#53]
## User Story 
As a user, I want to be able to navigate back to the view study set page, so I can study other things. 

## Sub-tasks 
- [ ] Create ribbon with an arrow and name of the study set 
- [ ] When arrow/name is clicked, navigate back to the View Page for the current study set 
- [ ] Add to study flashcard and study sequence pages

## Notes
- depends on #48 #6 #39
