### ISSUE TITLE
SI.1 Create Sign in page

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#54]
## User Story 
As a user, I want to be able to access the Ponder app with my google account, so I can access my sets. 

## Sub-tasks 
- [x] Create google developer account/id 
- [ ] Install login dependencies and add to angular app 
- [ ] Implement filter for non-logged in user 
- [ ] Navigate to Homepage after user authenticates
