### ISSUE TITLE
Misc.6 Create Study Set State Holder

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#56]
## User Story
As the user, I want the information in the study sets to be consistent when I go to different screens, so I don't get confused.

## Sub-tasks
- [x] Create Flashcard data model
- [x] Create Sequence data model
- [x] Create Study Set data model
