### ISSUE TITLE
V.4 Add study button/menu

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#7]
## User Story
As a user, I want to be able to start studying the study, so I can learn. 

## Sub-tasks
- [ ] Create study button/menu
- [ ] Add navigation to study flashcard page
- [ ] Add navigation to study sequence page
