### ISSUE TITLE
V.3 Add share button to view study set page

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#8]
### User Story
As a user, I want to be able to share a study set, so I can collaborate with my classmates.   

### Sub-tasks
- [x] Add share button
- [x] Create share link UI component
- [x] Implement share link component overlay showing url on button click

## Notes
- Depends on #6
