### ISSUE TITLE
V.6 Implement Sequence tab on View page

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#9]
## User Story
As a user, I want to be able to view a list of all the terms and definitions in each sequence that is in a study set, so I know what I will be studying. I should be able to select different sequences I want to view. 

## Sub-tasks
- [x] Create card component (for list; can probably reuse from V.5 if dynamically sized)  
- [x] Create side panel for selecting sequences in the “contents” container under tabs 
- [x] Show list of cards in the selected sequence next to side panel 

## Notes
- Depends on #6
