### ISSUE TITLE
Misc.8 User Service for Cloud

### ISSUE THREAD

**Issue by B-Yamawaki** [PonderTeam/ponder-app#95]
## User Story
As a user, I want to be able to have customized information of my account loaded into the app so that I can see my data.

## Sub-tasks
- [ ] Create user collection
- [ ] Implement the user-info service
 - [ ] Load User
- [ ] Test User service
